### ISSUE TITLE
POST /apis/apps/v1/deployments => HTTP 405 Method Not Allowed

### ISSUE THREAD

**Issue by Kerwood** [kontena/mortar#120]
Trying to deploy a simple deployment.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-mqtt
  labels:
    app: mosquitto-mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto-mqtt
  template:
    metadata:
      labels:
        app: mosquitto-mqtt
    spec:
      containers:
      - name: mosquitto-mqtt
        image: eclipse-mosquitto
        imagePullPolicy: Always
        ports:
        - containerPort: 1883
          name: incoming
        - containerPort: 9001
          name: websockets
        volumeMounts:
        - name: mosquitto-data
          mountPath: /mosquitto/data
      volumes:
      - name: mosquitto-data
        hostPath:
          path: /home/k8s-storage/mqtt/data
          type: Directory
```

Getting this error
```
Traceback (most recent call last):
        14: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/bin/mortar:23:in `<main>'
        13: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/bin/mortar:23:in `load'
        12: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/kontena-mortar-0.4.6/bin/mortar:13:in `<top (required)>'
        11: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/clamp-1.3.1/lib/clamp/command.rb:140:in `run'
        10: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/clamp-1.3.1/lib/clamp/command.rb:66:in `run'
         9: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/clamp-1.3.1/lib/clamp/subcommand/execution.rb:18:in `execute'
         8: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/clamp-1.3.1/lib/clamp/command.rb:66:in `run'
         7: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/kontena-mortar-0.4.6/lib/mortar/fire_command.rb:66:in `execute'
         6: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/k8s-client-0.10.4/lib/k8s/stack.rb:100:in `apply'
         5: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/k8s-client-0.10.4/lib/k8s/stack.rb:100:in `map'
         4: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/k8s-client-0.10.4/lib/k8s/stack.rb:103:in `block in apply'
         3: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/k8s-client-0.10.4/lib/k8s/client.rb:225:in `create_resource'
         2: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/k8s-client-0.10.4/lib/k8s/resource_client.rb:148:in `create_resource'
         1: from /__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/k8s-client-0.10.4/lib/k8s/transport.rb:287:in `request'
/__enclose_io_memfs__/lib/ruby/gems/2.5.0/gems/k8s-client-0.10.4/lib/k8s/transport.rb:263:in `parse_response': POST /apis/apps/v1/deployments => HTTP 405 Method Not Allowed: the server does not allow this method on the requested resource (K8s::Error::MethodNotAllowed)
```
